import {
  SCENIC_IMAGE_PRESETS,
  type ScenicImagePreset,
  type ScenicImageRegion,
  type ScenicImageAspectRatio,
  type ScenicImageMood,
} from "@/lib/scenic-image-prompts";

export type ScenicCollection =
  | "USA Featured"
  | "USA More Parks"
  | "Canada"
  | "Japan"
  | "Europe — Switzerland / Norway / Iceland / Alps"
  | "World Scenic Wildlife";

export type ExpandedScenicImagePreset = ScenicImagePreset & {
  collection: ScenicCollection;
};

export const SCENIC_COLLECTIONS: Array<ScenicCollection | "All"> = [
  "All",
  "USA Featured",
  "USA More Parks",
  "Canada",
  "Japan",
  "Europe — Switzerland / Norway / Iceland / Alps",
  "World Scenic Wildlife",
];

const USA_FEATURED_IDS = new Set([
  "grand-teton-schwabacher-elk",
  "yellowstone-lamar-bison-dawn",
  "yellowstone-hayden-valley-river",
  "glacier-logan-pass-goats",
  "yosemite-valley-deer-meadow",
  "rocky-mountain-elk-aspen",
  "denali-tundra-caribou",
  "mount-rainier-wildflower-meadow",
  "olympic-rainforest-elk",
  "zion-canyon-bighorn",
  "grand-canyon-elk-rim",
]);

function collectionForExistingPreset(preset: ScenicImagePreset): ScenicCollection {
  if (preset.region === "Canada") return "Canada";
  if (USA_FEATURED_IDS.has(preset.id)) return "USA Featured";
  return "USA More Parks";
}

function p(input: Omit<ExpandedScenicImagePreset, "viralScore"> & { viralScore?: number }): ExpandedScenicImagePreset {
  return {
    viralScore: input.viralScore ?? 86,
    ...input,
  };
}

const MORE_PRESETS: ExpandedScenicImagePreset[] = [
  p({
    id: "katmai-brown-bear-river",
    collection: "USA Featured",
    region: "USA",
    country: "USA",
    stateOrProvince: "Alaska",
    parkName: "Katmai National Park and Preserve",
    title: "Katmai Brown Bear River Landscape",
    landmarkStyle: "Brooks River inspired salmon stream and volcanic Alaska wilderness",
    locationStyle: "Katmai National Park inspired Alaskan river wilderness, peaceful non-graphic bear scene",
    compositionSignature: "clear river foreground, brown bear fishing calmly in midground, volcanic mountains and spruce flats behind",
    background: "low volcanic mountains, cool Alaska sky, distant spruce and alder flats, pale mist over the river corridor",
    midground: "wide shallow river with rounded stones, one brown bear standing calmly in water, natural scale and spacing",
    foreground: "clear rippling water, wet river stones, low grass and willow, clean highlights without splashing chaos",
    defaultWildlife: "Grizzly Bear",
    wildlifeBehavior: "brown bear standing calmly in a shallow river, non-aggressive, detailed wet fur, natural fishing posture without blood or gore",
    bestSeason: "late summer salmon season atmosphere",
    bestLight: "soft overcast Alaska daylight with clean river reflections",
    cameraLook: "premium wildlife documentary landscape still, long-lens compression, crisp bear detail and natural color",
    realismLocks: "accurate bear anatomy, realistic river depth, no graphic fish, no aggressive behavior, no tourist platforms",
    avoidTerms: "no people, no platforms, no blood, no fish gore, no bear attack",
    caption: "A quiet bear moment in Alaska wild country.",
    hashtags: ["#Katmai", "#Alaska", "#BrownBear", "#WildlifePhotography", "#USA"],
    viralScore: 96,
  }),
  p({
    id: "redwood-elk-giants",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "California",
    parkName: "Redwood National and State Parks",
    title: "Redwood Elk Among Giants",
    landmarkStyle: "coastal redwood grove and fern forest inspired scene",
    locationStyle: "Redwood National and State Parks inspired ancient forest clearing",
    compositionSignature: "fern foreground, Roosevelt elk midground, enormous redwood trunks towering vertically behind",
    background: "massive redwood trunks, soft coastal fog, dark green canopy, shafts of diffused light",
    midground: "small forest clearing with Roosevelt elk standing calmly between giant trees",
    foreground: "sword ferns, moss, fallen needles, damp forest floor, small wildflowers",
    defaultWildlife: "Elk",
    wildlifeBehavior: "Roosevelt elk standing calmly in a redwood clearing, natural scale against huge trees, realistic antlers and damp coat",
    bestSeason: "spring or misty autumn",
    bestLight: "soft fog-filtered morning light",
    cameraLook: "vertical forest landscape, strong scale contrast, documentary realism, rich natural greens",
    realismLocks: "accurate elk scale, believable redwood size, natural forest clutter, no tourists or roads",
    avoidTerms: "no people, no road, no cabins, no cartoon moss",
    caption: "Small wild life beneath ancient giants.",
    hashtags: ["#Redwoods", "#California", "#Elk", "#ForestPhotography", "#USA"],
    viralScore: 91,
  }),
  p({
    id: "point-reyes-tule-elk-coast",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "California",
    parkName: "Point Reyes National Seashore",
    title: "Point Reyes Tule Elk Ocean Cliffs",
    landmarkStyle: "coastal bluff and Pacific headland inspired scene",
    locationStyle: "Point Reyes inspired California coastal grassland and ocean cliff landscape",
    compositionSignature: "gold coastal grass foreground, tule elk on bluff midground, blue Pacific and fog bank behind",
    background: "Pacific Ocean horizon, coastal fog, rugged cliffs, soft blue-gray sky",
    midground: "tule elk standing calmly on safe coastal grassland far from the cliff edge",
    foreground: "wind-bent grasses, coastal wildflowers, sandy soil, low shrubs",
    defaultWildlife: "Elk",
    wildlifeBehavior: "tule elk standing peacefully on a coastal bluff meadow, realistic antlers, natural small herd spacing",
    bestSeason: "late spring or golden autumn",
    bestLight: "soft coastal golden hour with marine haze",
    cameraLook: "California coastal wildlife landscape, airy depth, natural muted color",
    realismLocks: "safe bluff distance, accurate tule elk scale, realistic ocean haze, no fences",
    avoidTerms: "no tourists, no fences, no road, no lighthouse building",
    caption: "Wild coastal calm above the Pacific.",
    hashtags: ["#PointReyes", "#California", "#TuleElk", "#PacificCoast", "#Wildlife"],
    viralScore: 88,
  }),
  p({
    id: "acadia-rocky-coast-deer",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "Maine",
    parkName: "Acadia National Park",
    title: "Acadia Rocky Coast Deer Sunrise",
    landmarkStyle: "rocky Atlantic coastline and spruce headland inspired scene",
    locationStyle: "Acadia National Park inspired Maine coast landscape",
    compositionSignature: "pink granite rocks foreground, deer near spruce edge, Atlantic sunrise and waves behind",
    background: "cold Atlantic water, rocky islands, spruce-covered headlands, sunrise clouds",
    midground: "quiet coastal meadow and spruce edge with white-tailed deer standing calmly",
    foreground: "pink granite slabs, low blueberry shrubs, coastal grasses, small tide pools",
    defaultWildlife: "White-tailed Deer",
    wildlifeBehavior: "white-tailed deer standing calmly near a spruce edge, natural scale, realistic ears and slender legs",
    bestSeason: "early autumn or summer sunrise",
    bestLight: "soft Atlantic sunrise with warm rim light on rocks",
    cameraLook: "clean coastal national park photograph, crisp rocks, realistic ocean texture",
    realismLocks: "accurate deer anatomy, believable waves, no tourists, no roads, no houses",
    avoidTerms: "no people, no road, no lighthouse, no buildings",
    caption: "Atlantic sunrise meets quiet wildlife.",
    hashtags: ["#Acadia", "#Maine", "#Deer", "#AtlanticCoast", "#Nature"],
    viralScore: 87,
  }),
  p({
    id: "big-bend-black-bear-desert",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "Texas",
    parkName: "Big Bend National Park",
    title: "Big Bend Black Bear Desert Mountains",
    landmarkStyle: "Chisos Mountains and desert wash inspired scene",
    locationStyle: "Big Bend National Park inspired desert mountain wilderness",
    compositionSignature: "ocotillo and desert rocks foreground, black bear distant midground, Chisos-style ridges behind",
    background: "purple desert mountain ridges, warm sky, limestone cliffs, wide open Chihuahuan Desert air",
    midground: "dry wash and mesquite flats with a black bear foraging calmly at safe distance",
    foreground: "ocotillo, agave, desert grasses, warm stones, small cactus blooms",
    defaultWildlife: "Black Bear",
    wildlifeBehavior: "black bear foraging calmly in a desert mountain wash, natural scale, non-aggressive posture",
    bestSeason: "spring desert bloom or clear autumn",
    bestLight: "warm late afternoon desert side light",
    cameraLook: "Southwest wilderness landscape, rich but natural desert color, clean vertical framing",
    realismLocks: "correct bear scale, realistic desert plants, no aggressive pose, no oversaturation",
    avoidTerms: "no people, no roads, no cabins, no bear attack",
    caption: "Wild calm in the desert mountains.",
    hashtags: ["#BigBend", "#Texas", "#BlackBear", "#DesertWildlife", "#USA"],
    viralScore: 84,
  }),
  p({
    id: "bryce-canyon-pronghorn-hoodoos",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "Utah",
    parkName: "Bryce Canyon National Park",
    title: "Bryce Canyon Pronghorn Hoodoo Sunrise",
    landmarkStyle: "amphitheater hoodoos and high desert meadow inspired scene",
    locationStyle: "Bryce Canyon inspired high desert rim and hoodoo landscape",
    compositionSignature: "sage and grass foreground, pronghorn midground, orange hoodoo amphitheater behind",
    background: "orange limestone hoodoos, distant forested rim, pale blue morning sky",
    midground: "high desert meadow with pronghorn standing calmly, natural spacing and scale",
    foreground: "sagebrush, dry grass, small wildflowers, pale limestone stones",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "pronghorn-like high desert ungulate standing calmly in open meadow, slender legs, natural alert posture",
    bestSeason: "spring or autumn",
    bestLight: "sunrise glow across orange hoodoos",
    cameraLook: "clean desert postcard realism, high detail rock forms, readable wildlife silhouette",
    realismLocks: "believable hoodoo geology, natural animal scale, no impossible cliff pose",
    avoidTerms: "no tourists, no railings, no roads, no fantasy orange saturation",
    caption: "A quiet morning above the hoodoos.",
    hashtags: ["#BryceCanyon", "#Utah", "#Wildlife", "#DesertLandscape", "#USA"],
    viralScore: 85,
  }),
  p({
    id: "arches-bighorn-red-rock",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "Utah",
    parkName: "Arches National Park",
    title: "Arches Desert Bighorn Red Rock",
    landmarkStyle: "red sandstone arch country and desert wash inspired scene",
    locationStyle: "Arches National Park inspired red-rock desert landscape",
    compositionSignature: "desert plants foreground, bighorn sheep midground, sandstone fins and arch-like forms behind",
    background: "red sandstone fins, distant arch-shaped rock forms, La Sal-style mountains faint in haze",
    midground: "desert bighorn sheep standing calmly on sandy wash edge",
    foreground: "cryptobiotic soil kept undisturbed, desert grasses, small stones, flowering cactus",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "bighorn sheep standing peacefully near red sandstone, accurate horns and grounded hooves",
    bestSeason: "spring or autumn desert light",
    bestLight: "warm golden hour side light on red rock",
    cameraLook: "Southwest national park travel-photo realism, clean composition, natural colors",
    realismLocks: "accurate bighorn anatomy, no rock distortion, no dust, no people",
    avoidTerms: "no tourists, no roads, no signs, no fighting sheep",
    caption: "Red rock country, quiet wild life.",
    hashtags: ["#ArchesNationalPark", "#Utah", "#BighornSheep", "#RedRock", "#USA"],
    viralScore: 86,
  }),
  p({
    id: "theodore-roosevelt-bison-badlands",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "North Dakota",
    parkName: "Theodore Roosevelt National Park",
    title: "Theodore Roosevelt Bison Badlands",
    landmarkStyle: "North Dakota badlands and prairie river breaks inspired scene",
    locationStyle: "Theodore Roosevelt National Park inspired prairie badlands",
    compositionSignature: "prairie grass foreground, bison midground, painted buttes and cottonwoods behind",
    background: "striped badlands buttes, cottonwood draws, big northern prairie sky",
    midground: "bison grazing calmly on rolling prairie bench, natural herd spacing",
    foreground: "mixed prairie grass, sage, small yellow flowers, dry clay stones without dust",
    defaultWildlife: "Bison",
    wildlifeBehavior: "bison grazing peacefully in North Dakota badlands, realistic shaggy coat, grounded hooves",
    bestSeason: "late spring or golden autumn",
    bestLight: "warm sunset light across badlands layers",
    cameraLook: "American prairie documentary landscape, natural color, clean depth",
    realismLocks: "accurate bison shape, realistic prairie, no road or cars, no dust cloud",
    avoidTerms: "no tourists, no vehicles, no roads, no charging bison",
    caption: "A quiet giant in painted prairie country.",
    hashtags: ["#TheodoreRooseveltNationalPark", "#NorthDakota", "#Bison", "#Prairie", "#USA"],
    viralScore: 84,
  }),
  p({
    id: "custer-state-park-bison",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "South Dakota",
    parkName: "Custer State Park",
    title: "Custer State Park Bison Hills",
    landmarkStyle: "Black Hills prairie and granite outcrop inspired scene",
    locationStyle: "Custer State Park inspired Black Hills bison landscape",
    compositionSignature: "rolling grass foreground, bison herd midground, pine and granite Black Hills behind",
    background: "dark pine hills, granite outcrops, soft clouds, open Black Hills sky",
    midground: "small bison herd grazing calmly with one bull readable in profile",
    foreground: "green prairie grass, small wildflowers, rounded stones, clean natural footing",
    defaultWildlife: "Bison",
    wildlifeBehavior: "bison herd grazing peacefully, realistic shaggy coats, natural spacing and grounded hooves",
    bestSeason: "summer or early autumn",
    bestLight: "late-day side light with long prairie shadows",
    cameraLook: "clean state park wildlife landscape, social-post friendly, realistic color",
    realismLocks: "natural bison scale, no road, no vehicles, no dust clouds",
    avoidTerms: "no cars, no tourists, no fences, no charging herd",
    caption: "Wild prairie calm in the Black Hills.",
    hashtags: ["#CusterStatePark", "#SouthDakota", "#Bison", "#BlackHills", "#Wildlife"],
    viralScore: 83,
  }),
  p({
    id: "bosque-cranes-sunrise",
    collection: "USA More Parks",
    region: "USA",
    country: "USA",
    stateOrProvince: "New Mexico",
    parkName: "Bosque del Apache National Wildlife Refuge",
    title: "Bosque del Apache Crane Sunrise",
    landmarkStyle: "Rio Grande wetland refuge and winter bird flyout inspired scene",
    locationStyle: "Bosque del Apache inspired New Mexico wetland sunrise",
    compositionSignature: "shallow water foreground, cranes in midground, sunrise sky and cottonwoods behind",
    background: "warm desert sunrise, distant Chupadera-style mountains, cottonwood silhouettes, glowing clouds",
    midground: "sandhill cranes standing and lifting calmly from shallow water, natural flock spacing",
    foreground: "glassy water reflections, reeds, frost on marsh grass, soft ripples",
    defaultWildlife: "Great Blue Heron",
    wildlifeBehavior: "sandhill crane-like tall wetland birds standing calmly in shallow water, accurate legs and wing shapes",
    bestSeason: "winter migration season",
    bestLight: "fiery sunrise reflected in still wetland water",
    cameraLook: "bird photography landscape, long-lens compression, clean reflection and natural color",
    realismLocks: "accurate bird anatomy, realistic reflections, no crowding, no text",
    avoidTerms: "no photographers, no boardwalk, no roads, no artificial pond edge",
    caption: "Morning wings over the New Mexico wetlands.",
    hashtags: ["#BosqueDelApache", "#NewMexico", "#BirdPhotography", "#Wildlife", "#USA"],
    viralScore: 88,
  }),
  p({
    id: "kluane-dall-sheep-icefield",
    collection: "Canada",
    region: "Canada",
    country: "Canada",
    stateOrProvince: "Yukon",
    parkName: "Kluane National Park and Reserve",
    title: "Kluane Dall Sheep Icefield Vista",
    landmarkStyle: "Yukon icefield and alpine tundra inspired scene",
    locationStyle: "Kluane National Park inspired subarctic mountain wilderness",
    compositionSignature: "tundra foreground, Dall sheep on alpine slope, huge icefield and glaciated peaks behind",
    background: "white icefield, crevassed glaciers, dark storm edge, thin northern light",
    midground: "safe alpine tundra slope with Dall sheep standing calmly and naturally spaced",
    foreground: "lichen stones, dwarf willow, autumn tundra colors, patches of snow",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "Dall sheep-like white mountain sheep standing calmly on tundra slope, realistic horns and hooves",
    bestSeason: "late summer or early autumn",
    bestLight: "dramatic clear subarctic side light",
    cameraLook: "remote Yukon wilderness photo, epic glacier depth, restrained natural color",
    realismLocks: "safe slope, accurate sheep anatomy, realistic glacier scale, no fantasy ice colors",
    avoidTerms: "no people, no aircraft, no roads, no impossible cliff pose",
    caption: "Northern silence above the icefields.",
    hashtags: ["#Kluane", "#Yukon", "#DallSheep", "#Canada", "#Wilderness"],
    viralScore: 90,
  }),
  p({
    id: "waterton-lakes-bighorn",
    collection: "Canada",
    region: "Canada",
    country: "Canada",
    stateOrProvince: "Alberta",
    parkName: "Waterton Lakes National Park",
    title: "Waterton Lakes Bighorn Mountain Shore",
    landmarkStyle: "prairie-meets-mountain lake valley inspired scene",
    locationStyle: "Waterton Lakes inspired Canadian Rockies lake and grassland edge",
    compositionSignature: "windy lake foreground, bighorn sheep midground, steep mountains and prairie edge behind",
    background: "steep Rocky Mountain walls, deep blue lake, sweeping prairie foothills, clean clouds",
    midground: "bighorn sheep standing calmly near rocky shore and grass slope",
    foreground: "lake stones, grass, small wildflowers, wind ripples on water",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "bighorn sheep standing calmly near a mountain lake shore, accurate horns and grounded hooves",
    bestSeason: "summer or autumn",
    bestLight: "late afternoon mountain light with clean wind texture",
    cameraLook: "Canadian Rockies landscape realism, strong lake-to-mountain depth",
    realismLocks: "accurate sheep horns, realistic lake color, safe shoreline, no tourist buildings",
    avoidTerms: "no roads, no hotels, no people, no fighting sheep",
    caption: "Where prairie wind meets mountain water.",
    hashtags: ["#WatertonLakes", "#Alberta", "#BighornSheep", "#Canada", "#Wildlife"],
    viralScore: 86,
  }),
  p({
    id: "churchill-polar-bear-tundra",
    collection: "Canada",
    region: "Canada",
    country: "Canada",
    stateOrProvince: "Manitoba",
    parkName: "Churchill Wildlife Region",
    title: "Churchill Polar Bear Tundra Light",
    landmarkStyle: "Hudson Bay tundra and northern lights inspired scene",
    locationStyle: "Churchill Manitoba inspired subarctic tundra wildlife landscape",
    compositionSignature: "snowy tundra foreground, distant polar bear midground, Hudson Bay sky and aurora glow behind",
    background: "frozen bay horizon, low tundra willows, pale aurora ribbons, cold blue twilight sky",
    midground: "polar bear walking calmly at safe distance, small-to-medium in frame, non-aggressive posture",
    foreground: "snow crust, tundra grass tips, ice patches, clean wind-shaped texture",
    defaultWildlife: "Grizzly Bear",
    wildlifeBehavior: "polar bear-like white bear walking calmly across tundra at safe distance, realistic scale and paws, non-aggressive",
    bestSeason: "late autumn / early winter",
    bestLight: "blue-hour Arctic twilight with subtle aurora",
    cameraLook: "premium northern wildlife landscape, cold color palette, realistic snow detail",
    realismLocks: "safe distance, correct bear anatomy, realistic snow and aurora, no vehicles",
    avoidTerms: "no tundra buggy, no people, no town, no aggressive bear",
    caption: "Northern light over quiet tundra.",
    hashtags: ["#Churchill", "#Manitoba", "#PolarBear", "#Canada", "#Wildlife"],
    viralScore: 93,
  }),
  p({
    id: "gros-morne-moose-fjord",
    collection: "Canada",
    region: "Canada",
    country: "Canada",
    stateOrProvince: "Newfoundland and Labrador",
    parkName: "Gros Morne National Park",
    title: "Gros Morne Moose Fjord Valley",
    landmarkStyle: "fjord-like freshwater valley and boreal hills inspired scene",
    locationStyle: "Gros Morne National Park inspired Newfoundland mountain fjord landscape",
    compositionSignature: "wet meadow foreground, moose midground, steep green fjord walls and water behind",
    background: "steep glacial valley walls, dark water, boreal slopes, low Atlantic clouds",
    midground: "moose standing calmly near a wet meadow edge, natural scale and long legs",
    foreground: "bog grass, small flowers, wet stones, shallow pools with reflections",
    defaultWildlife: "Moose",
    wildlifeBehavior: "moose standing peacefully in a wet meadow near water, accurate long legs and broad muzzle",
    bestSeason: "summer or autumn",
    bestLight: "soft overcast Atlantic light",
    cameraLook: "moody Canadian Atlantic wilderness photo, natural muted color, deep valley framing",
    realismLocks: "accurate moose anatomy, realistic wetland, no boats or people, no fantasy fjord colors",
    avoidTerms: "no buildings, no tourists, no road, no boats",
    caption: "Quiet moose country in Newfoundland wilderness.",
    hashtags: ["#GrosMorne", "#Newfoundland", "#Moose", "#Canada", "#Wilderness"],
    viralScore: 85,
  }),
  p({
    id: "shiretoko-fox-sea-ice",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Hokkaido, Japan",
    parkName: "Shiretoko National Park",
    title: "Shiretoko Ezo Fox Sea-Ice Coast",
    landmarkStyle: "Hokkaido sea-ice coastline and wild forest inspired scene",
    locationStyle: "Shiretoko National Park inspired Hokkaido winter coastal wilderness",
    compositionSignature: "snowy shoreline foreground, Ezo red fox midground, drift ice and forested cliffs behind",
    background: "Okhotsk-style sea ice, dark winter forest cliffs, cold blue sky, low coastal mist",
    midground: "Ezo red fox standing calmly on snow near the coast, small-to-medium in frame",
    foreground: "wind-shaped snow, ice pieces, beach stones, sparse winter grass",
    defaultWildlife: "Black Bear",
    wildlifeBehavior: "Ezo red fox with orange winter coat and white chest standing calmly on snowy coast, realistic paws and tail",
    bestSeason: "deep winter sea-ice season",
    bestLight: "cold morning side light with blue shadows",
    cameraLook: "Japanese national park winter wildlife photo, crisp snow texture, clean composition",
    realismLocks: "accurate fox scale, realistic sea ice, no people, no buildings, no anime look",
    avoidTerms: "no tourists, no roads, no houses, no cartoon style",
    caption: "Winter quiet on Hokkaido’s wild coast.",
    hashtags: ["#Shiretoko", "#Hokkaido", "#Japan", "#WildlifePhotography", "#Nature"],
    viralScore: 94,
  }),
  p({
    id: "kushiro-cranes-snow-wetland",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Hokkaido, Japan",
    parkName: "Kushiroshitsugen National Park",
    title: "Kushiro Red-Crowned Cranes Snow Wetland",
    landmarkStyle: "snowy Hokkaido marsh and crane dance inspired scene",
    locationStyle: "Kushiroshitsugen National Park inspired winter wetland",
    compositionSignature: "snowy reed foreground, red-crowned cranes midground, misty wetland and pale sunrise behind",
    background: "frozen marsh, reed beds, low winter fog, pale pink sunrise sky",
    midground: "red-crowned cranes standing calmly with elegant spacing, one wing partially open",
    foreground: "snow-covered reeds, shallow icy water, soft crane reflections, frost texture",
    defaultWildlife: "Great Blue Heron",
    wildlifeBehavior: "red-crowned cranes with white bodies, black necks, red crown marks, accurate long legs and graceful posture",
    bestSeason: "winter snow season",
    bestLight: "soft sunrise light through cold wetland mist",
    cameraLook: "elegant bird photography landscape, high-detail feathers, quiet Japanese winter mood",
    realismLocks: "accurate crane anatomy, realistic snow and reeds, no crowding, no people",
    avoidTerms: "no tourists, no feeders, no fences, no cartoon birds",
    caption: "A quiet crane morning in Hokkaido snow.",
    hashtags: ["#Kushiro", "#Hokkaido", "#Japan", "#Cranes", "#Wildlife"],
    viralScore: 96,
  }),
  p({
    id: "daisetsuzan-deer-autumn",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Hokkaido, Japan",
    parkName: "Daisetsuzan National Park",
    title: "Daisetsuzan Ezo Deer Autumn Valley",
    landmarkStyle: "Hokkaido volcanic alpine valley and autumn forest inspired scene",
    locationStyle: "Daisetsuzan National Park inspired alpine autumn landscape",
    compositionSignature: "red-gold alpine plants foreground, Ezo deer midground, volcanic peaks and snow dusting behind",
    background: "volcanic ridges, early snow patches, larch and birch forest, crisp Hokkaido sky",
    midground: "Ezo deer standing peacefully near a mountain stream and autumn shrubs",
    foreground: "red alpine shrubs, golden grasses, stream stones, low mist",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "Ezo deer with natural brown coat and alert ears standing calmly in autumn alpine valley",
    bestSeason: "peak autumn color",
    bestLight: "clear golden-hour alpine side light",
    cameraLook: "Japanese alpine wildlife landscape, crisp seasonal color, documentary realism",
    realismLocks: "accurate deer scale, realistic alpine vegetation, no oversaturated reds, no people",
    avoidTerms: "no roads, no ropeway, no tourists, no buildings",
    caption: "Autumn color across Hokkaido high country.",
    hashtags: ["#Daisetsuzan", "#Hokkaido", "#Japan", "#Deer", "#Autumn"],
    viralScore: 90,
  }),
  p({
    id: "jigokudani-snow-monkeys",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Nagano, Japan",
    parkName: "Joshin'etsukogen National Park / Jigokudani",
    title: "Jigokudani Snow Monkey Winter Steam",
    landmarkStyle: "snowy hot spring valley and macaque habitat inspired scene",
    locationStyle: "Jigokudani inspired Nagano winter snow monkey valley",
    compositionSignature: "snowy rocks foreground, Japanese macaque midground, steam and cedar forest behind",
    background: "snow-covered cedar slopes, rising hot spring steam, narrow winter valley, soft gray sky",
    midground: "Japanese macaque sitting calmly near steaming water, natural fur detail, peaceful behavior",
    foreground: "snow on dark rocks, warm steam, icy stream edge, clean winter texture",
    defaultWildlife: "No wildlife / landscape only",
    wildlifeBehavior: "Japanese macaque with thick winter fur sitting calmly beside steam, realistic face and hands, non-comical posture",
    bestSeason: "deep winter snow",
    bestLight: "soft overcast snow light with warm steam contrast",
    cameraLook: "documentary Japanese winter wildlife photo, gentle steam, realistic snow and fur",
    realismLocks: "accurate macaque anatomy, no human-like expression exaggeration, no tourists, no buildings",
    avoidTerms: "no people, no fences, no towels, no cartoon monkey",
    caption: "Steam and snow in a quiet mountain valley.",
    hashtags: ["#Jigokudani", "#Nagano", "#Japan", "#SnowMonkey", "#Wildlife"],
    viralScore: 95,
  }),
  p({
    id: "fuji-lake-deer",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Yamanashi / Shizuoka, Japan",
    parkName: "Fuji-Hakone-Izu National Park",
    title: "Mount Fuji Lake Deer Morning",
    landmarkStyle: "Fuji Five Lakes style reflection and forest edge inspired scene",
    locationStyle: "Fuji-Hakone-Izu National Park inspired Mount Fuji lake landscape",
    compositionSignature: "lake stones foreground, deer near water midground, Mount Fuji reflection behind",
    background: "snow-capped Mount Fuji, calm lake reflection, pine forest edge, clear dawn sky",
    midground: "deer standing peacefully near a quiet lake shore, natural scale and spacing",
    foreground: "smooth lake stones, reeds, small wildflowers, clean water ripples",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "deer standing calmly near a lake shore, realistic anatomy, small-to-medium in frame",
    bestSeason: "spring or crisp winter morning",
    bestLight: "soft sunrise light with clean mountain reflection",
    cameraLook: "classic Japanese landscape realism, balanced reflection, social-post clean composition",
    realismLocks: "realistic Fuji scale, no buildings, no tourist boats, accurate deer anatomy",
    avoidTerms: "no people, no city, no power lines, no buildings",
    caption: "A quiet morning under Mount Fuji.",
    hashtags: ["#MountFuji", "#Japan", "#FujiHakoneIzu", "#Nature", "#Wildlife"],
    viralScore: 94,
  }),
  p({
    id: "yakushima-deer-cedar",
    collection: "Japan",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Kagoshima, Japan",
    parkName: "Yakushima National Park",
    title: "Yakushima Deer Ancient Cedar Forest",
    landmarkStyle: "mossy ancient cedar rainforest inspired scene",
    locationStyle: "Yakushima National Park inspired subtropical cedar forest",
    compositionSignature: "moss and roots foreground, Yakushima deer midground, ancient cedar trunks behind",
    background: "massive cedar trunks, dense moss, misty green understory, soft rainforest light",
    midground: "small Yakushima deer standing calmly near tree roots, natural scale and wet coat detail",
    foreground: "moss-covered roots, ferns, wet stones, shallow forest stream",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "small island deer standing calmly in mossy cedar forest, realistic ears and legs",
    bestSeason: "rainy spring or lush summer",
    bestLight: "soft rainforest diffusion with gentle mist",
    cameraLook: "moody Japanese forest documentary still, rich natural greens, no fantasy glow",
    realismLocks: "accurate small deer scale, realistic moss, no anime look, no human structures",
    avoidTerms: "no tourists, no boardwalk, no signs, no cartoon greens",
    caption: "Ancient forest quiet on Yakushima.",
    hashtags: ["#Yakushima", "#Japan", "#Forest", "#Deer", "#NaturePhotography"],
    viralScore: 91,
  }),
  p({
    id: "zermatt-matterhorn-ibex",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Valais, Switzerland",
    parkName: "Zermatt / Matterhorn Region",
    title: "Matterhorn Alpine Ibex Meadow",
    landmarkStyle: "Zermatt alpine meadow and Matterhorn-style peak inspired scene",
    locationStyle: "Swiss Alps inspired Matterhorn region alpine landscape",
    compositionSignature: "alpine flowers foreground, ibex midground, Matterhorn-style pyramid peak behind",
    background: "sharp snow-streaked pyramid peak, high alpine sky, glacier patches, dark rock ridges",
    midground: "alpine ibex standing calmly on a safe grassy ledge, natural scale and spacing",
    foreground: "edelweiss-like alpine flowers, short grass, lichen stones, clean mountain air",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "alpine ibex with long curved horns standing calmly on safe meadow ledge, grounded hooves, realistic coat",
    bestSeason: "summer alpine bloom",
    bestLight: "crisp morning alpenglow on the peak",
    cameraLook: "Swiss alpine postcard realism, premium travel photo, sharp peak detail and natural color",
    realismLocks: "accurate ibex horns, safe ledge, realistic mountain scale, no village buildings",
    avoidTerms: "no tourists, no ski lifts, no buildings, no impossible cliff pose",
    caption: "Alpine silence beneath the Matterhorn.",
    hashtags: ["#Switzerland", "#Matterhorn", "#Ibex", "#SwissAlps", "#Nature"],
    viralScore: 96,
  }),
  p({
    id: "swiss-national-park-chamois",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Graubünden, Switzerland",
    parkName: "Swiss National Park",
    title: "Swiss National Park Chamois Valley",
    landmarkStyle: "Engadin alpine valley and protected wilderness inspired scene",
    locationStyle: "Swiss National Park inspired Graubünden alpine valley",
    compositionSignature: "larch meadow foreground, chamois midground, limestone peaks and autumn valley behind",
    background: "gray limestone peaks, golden larch forest, clear alpine sky, distant valley layers",
    midground: "chamois standing calmly on an alpine meadow slope, small and naturally scaled",
    foreground: "short alpine grass, larch needles, wildflowers, weathered stones",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "chamois-like alpine ungulate standing calmly on meadow slope, slender horns, realistic legs",
    bestSeason: "autumn larch color or summer bloom",
    bestLight: "clear alpine side light with crisp shadows",
    cameraLook: "restrained European alpine documentary photo, clean depth and natural color",
    realismLocks: "accurate mountain ungulate scale, no villages, no fences, realistic alpine vegetation",
    avoidTerms: "no buildings, no roads, no tourists, no ski lifts",
    caption: "Quiet wild life in the Swiss Alps.",
    hashtags: ["#SwissNationalPark", "#Switzerland", "#Chamois", "#Alps", "#Wildlife"],
    viralScore: 89,
  }),
  p({
    id: "lauterbrunnen-deer-waterfalls",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Bernese Oberland, Switzerland",
    parkName: "Lauterbrunnen Valley",
    title: "Lauterbrunnen Deer Waterfall Valley",
    landmarkStyle: "Swiss waterfall valley and meadow inspired scene",
    locationStyle: "Lauterbrunnen inspired Bernese Oberland valley landscape",
    compositionSignature: "flower meadow foreground, deer midground, tall waterfall cliffs and alpine walls behind",
    background: "vertical green cliffs, thin waterfall ribbons, snow-touched peaks, soft valley clouds",
    midground: "deer grazing peacefully in a meadow away from buildings and paths",
    foreground: "Swiss meadow flowers, bright grass, stream stones, clean water sparkle",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "deer grazing calmly in a Swiss alpine meadow, natural scale, realistic ears and legs",
    bestSeason: "late spring / summer meadow bloom",
    bestLight: "soft morning valley light with gentle mist",
    cameraLook: "European alpine travel-photo realism, vertical postcard composition, natural greens",
    realismLocks: "realistic waterfall scale, accurate deer anatomy, no village buildings, no roads",
    avoidTerms: "no houses, no tourists, no cable cars, no roads",
    caption: "A quiet meadow below Swiss waterfalls.",
    hashtags: ["#Lauterbrunnen", "#Switzerland", "#SwissAlps", "#Deer", "#Nature"],
    viralScore: 94,
  }),
  p({
    id: "dovrefjell-musk-ox",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Trøndelag / Innlandet, Norway",
    parkName: "Dovrefjell-Sunndalsfjella National Park",
    title: "Dovrefjell Musk Ox Mountain Tundra",
    landmarkStyle: "Norwegian mountain tundra and musk ox range inspired scene",
    locationStyle: "Dovrefjell-Sunndalsfjella inspired Norway tundra wilderness",
    compositionSignature: "lichen tundra foreground, musk ox midground, rounded mountains and cold sky behind",
    background: "broad gray mountains, snow patches, low clouds, open Nordic tundra",
    midground: "musk ox standing calmly at safe distance, shaggy coat, natural heavy posture",
    foreground: "lichen, dwarf shrubs, wet stones, cold grass, patches of snow",
    defaultWildlife: "Bison",
    wildlifeBehavior: "musk ox with long shaggy brown coat and curved horns standing calmly on tundra, safe distance, non-aggressive",
    bestSeason: "autumn or early winter",
    bestLight: "cold low Nordic side light",
    cameraLook: "Norwegian wilderness documentary photo, muted natural color, strong animal silhouette",
    realismLocks: "accurate musk ox proportions, realistic tundra, no tourists, no road",
    avoidTerms: "no people, no road, no charging animal, no fantasy snowstorm",
    caption: "Ancient strength on Norway’s mountain tundra.",
    hashtags: ["#Norway", "#Dovrefjell", "#MuskOx", "#Wildlife", "#Tundra"],
    viralScore: 95,
  }),
  p({
    id: "lofoten-sea-eagle-fjords",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Nordland, Norway",
    parkName: "Lofoten Islands",
    title: "Lofoten Sea Eagle Fjord Cliffs",
    landmarkStyle: "dramatic Arctic coast and fjord cliffs inspired scene",
    locationStyle: "Lofoten Islands inspired Norwegian coastal mountain landscape",
    compositionSignature: "rocky shore foreground, sea eagle midground, sharp fjord peaks and cold ocean behind",
    background: "jagged coastal mountains, deep blue fjord water, cold clouds, distant fishing-free shoreline",
    midground: "white-tailed sea eagle gliding calmly above water or perched on a rock",
    foreground: "wet black rocks, seaweed, tide pools, cold water reflections",
    defaultWildlife: "Bald Eagle",
    wildlifeBehavior: "large sea eagle with broad wings and realistic feather anatomy, calm flight over fjord water",
    bestSeason: "summer midnight light or winter blue hour",
    bestLight: "soft Arctic side light with dramatic clouds",
    cameraLook: "epic Nordic coastal wildlife photo, cinematic but photoreal, restrained color",
    realismLocks: "accurate bird wings, realistic fjord scale, no villages, no boats",
    avoidTerms: "no houses, no boats, no people, no fantasy aurora unless requested",
    caption: "Wild wings over Arctic fjord water.",
    hashtags: ["#Lofoten", "#Norway", "#SeaEagle", "#Fjords", "#Wildlife"],
    viralScore: 93,
  }),
  p({
    id: "hardangervidda-reindeer-plateau",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Norway",
    parkName: "Hardangervidda National Park",
    title: "Hardangervidda Reindeer Plateau",
    landmarkStyle: "high mountain plateau and wild reindeer range inspired scene",
    locationStyle: "Hardangervidda inspired Norwegian plateau wilderness",
    compositionSignature: "tundra grass foreground, reindeer herd midground, wide plateau and snow ridges behind",
    background: "vast open plateau, snow streaks, low clouds, distant flat-topped mountains",
    midground: "small reindeer herd walking calmly with natural spacing",
    foreground: "lichen, wet grass, granite stones, shallow meltwater pools",
    defaultWildlife: "Caribou",
    wildlifeBehavior: "wild reindeer with realistic antlers and thick coats walking calmly across plateau, natural herd spacing",
    bestSeason: "late summer or autumn",
    bestLight: "low Nordic golden light under moving clouds",
    cameraLook: "wide Nordic wilderness still, minimal composition, natural color and scale",
    realismLocks: "accurate reindeer anatomy, realistic plateau vegetation, no road or cabins",
    avoidTerms: "no people, no cabins, no road, no fences",
    caption: "Wild reindeer crossing the high plateau.",
    hashtags: ["#Hardangervidda", "#Norway", "#Reindeer", "#Wilderness", "#Nature"],
    viralScore: 90,
  }),
  p({
    id: "iceland-puffin-cliffs",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Iceland",
    parkName: "Iceland South Coast / Sea Cliffs",
    title: "Iceland Puffin Sea Cliff Meadow",
    landmarkStyle: "Icelandic basalt sea cliff and puffin nesting meadow inspired scene",
    locationStyle: "Iceland south coast inspired basalt cliff wildlife landscape",
    compositionSignature: "green cliff grass foreground, puffins midground, black basalt cliffs and Atlantic waves behind",
    background: "black basalt sea cliffs, cold Atlantic waves, sea spray, moody North Atlantic clouds",
    midground: "puffins standing calmly near burrows, natural spacing and realistic beaks",
    foreground: "bright green cliff grass, small wildflowers, dark volcanic soil, wet stones",
    defaultWildlife: "Bald Eagle",
    wildlifeBehavior: "Atlantic puffins with colorful beaks and realistic feather texture standing calmly on grassy sea cliff",
    bestSeason: "summer puffin season",
    bestLight: "soft overcast coastal light",
    cameraLook: "Iceland wildlife travel photo, clean cliff depth, natural color and sea texture",
    realismLocks: "accurate puffin anatomy, safe cliff composition, no tourists, realistic ocean",
    avoidTerms: "no people, no fences, no buildings, no cartoon birds",
    caption: "Tiny wild color above the North Atlantic.",
    hashtags: ["#Iceland", "#Puffins", "#WildlifePhotography", "#Atlantic", "#Nature"],
    viralScore: 92,
  }),
  p({
    id: "iceland-reindeer-eastfjords",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "East Iceland",
    parkName: "Eastfjords Iceland",
    title: "Iceland Eastfjords Reindeer Valley",
    landmarkStyle: "East Iceland fjord valley and reindeer range inspired scene",
    locationStyle: "Eastfjords Iceland inspired coastal mountain wildlife landscape",
    compositionSignature: "mossy lava foreground, reindeer midground, fjord mountains and cold sea behind",
    background: "steep fjord mountains, cold blue water, low cloud ceiling, volcanic slopes",
    midground: "reindeer standing calmly in a broad valley, natural scale and spacing",
    foreground: "mossy lava stones, autumn grass, small streams, dark volcanic soil",
    defaultWildlife: "Caribou",
    wildlifeBehavior: "reindeer with accurate antlers and thick coat standing calmly in Icelandic valley",
    bestSeason: "autumn or winter edge",
    bestLight: "low Arctic side light through clouds",
    cameraLook: "Icelandic wilderness photo, muted cinematic realism, clean fjord depth",
    realismLocks: "accurate reindeer scale, realistic volcanic terrain, no roads, no houses",
    avoidTerms: "no people, no roads, no farms, no buildings",
    caption: "Reindeer silence in Iceland’s eastern fjords.",
    hashtags: ["#Iceland", "#Reindeer", "#Eastfjords", "#Wildlife", "#Nature"],
    viralScore: 88,
  }),
  p({
    id: "dolomites-ibex-alpine-lake",
    collection: "Europe — Switzerland / Norway / Iceland / Alps",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "South Tyrol, Italy",
    parkName: "Dolomites / South Tyrol",
    title: "Dolomites Ibex Alpine Lake",
    landmarkStyle: "jagged Dolomite peaks and turquoise alpine lake inspired scene",
    locationStyle: "Italian Dolomites inspired alpine wildlife landscape",
    compositionSignature: "alpine flowers foreground, ibex on safe rock midground, jagged Dolomite towers and lake behind",
    background: "pale limestone towers, turquoise alpine lake, dark pine slopes, clear mountain sky",
    midground: "ibex standing calmly on safe rocky slope, natural scale and realistic horns",
    foreground: "alpine flowers, lichen rocks, short grass, clean lake edge",
    defaultWildlife: "Bighorn Sheep",
    wildlifeBehavior: "alpine ibex with long curved horns standing calmly on safe rock, grounded hooves and realistic coat",
    bestSeason: "summer alpine bloom",
    bestLight: "warm alpenglow on pale limestone peaks",
    cameraLook: "premium European Alps travel poster realism, clean vertical depth, natural color",
    realismLocks: "accurate ibex horns, realistic lake color, no ski lifts, no buildings",
    avoidTerms: "no tourists, no roads, no huts, no cable cars",
    caption: "Wild alpine stillness in the Dolomites.",
    hashtags: ["#Dolomites", "#Italy", "#Ibex", "#Alps", "#Nature"],
    viralScore: 93,
  }),
  p({
    id: "new-zealand-kea-fiordland",
    collection: "World Scenic Wildlife",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "South Island, New Zealand",
    parkName: "Fiordland National Park",
    title: "Fiordland Kea Mountain Rainforest",
    landmarkStyle: "New Zealand fjord mountains and rainforest alpine edge inspired scene",
    locationStyle: "Fiordland National Park inspired New Zealand wilderness",
    compositionSignature: "wet moss foreground, kea bird midground, steep fjord mountains and waterfalls behind",
    background: "dark fjord mountains, misty waterfalls, deep rainforest slopes, moody clouds",
    midground: "kea perched calmly on a mossy rock, realistic feathers and curved beak",
    foreground: "wet moss, ferns, dark stones, small alpine plants, rain droplets",
    defaultWildlife: "Bald Eagle",
    wildlifeBehavior: "kea alpine parrot perched calmly, olive-green feathers with subtle orange underwing hints, accurate beak and claws",
    bestSeason: "rainy spring or summer",
    bestLight: "soft overcast mountain rain light",
    cameraLook: "New Zealand wilderness documentary still, moody natural color, high detail rain texture",
    realismLocks: "accurate kea anatomy, realistic rainforest, no people, no huts",
    avoidTerms: "no tourists, no roads, no buildings, no cartoon bird",
    caption: "Mountain rain and wild color in Fiordland.",
    hashtags: ["#NewZealand", "#Fiordland", "#Kea", "#Wildlife", "#Nature"],
    viralScore: 91,
  }),
  p({
    id: "finland-lapland-reindeer-aurora",
    collection: "World Scenic Wildlife",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Lapland, Finland",
    parkName: "Finnish Lapland",
    title: "Lapland Reindeer Aurora Forest",
    landmarkStyle: "snowy boreal forest and northern lights inspired scene",
    locationStyle: "Finnish Lapland inspired winter reindeer landscape",
    compositionSignature: "snowy pine foreground, reindeer midground, aurora and boreal forest behind",
    background: "dark boreal forest, green aurora ribbons, starry winter sky, soft snow-laden trees",
    midground: "reindeer standing calmly in snow, natural posture and accurate antlers",
    foreground: "powder snow, pine branches, blue shadows, clean tracks",
    defaultWildlife: "Caribou",
    wildlifeBehavior: "reindeer standing peacefully in snowy forest, accurate antlers, thick winter coat, grounded hooves",
    bestSeason: "deep winter",
    bestLight: "blue-hour snow light with subtle aurora glow",
    cameraLook: "Nordic winter wildlife wallpaper, realistic aurora, clean mobile composition",
    realismLocks: "accurate reindeer anatomy, realistic aurora, no buildings, no sleighs",
    avoidTerms: "no people, no cabins, no sleigh, no Christmas props",
    caption: "Northern lights over quiet reindeer country.",
    hashtags: ["#Lapland", "#Finland", "#Reindeer", "#Aurora", "#Nature"],
    viralScore: 94,
  }),
  p({
    id: "scotland-red-deer-highlands",
    collection: "World Scenic Wildlife",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Scottish Highlands, UK",
    parkName: "Scottish Highlands",
    title: "Scottish Highlands Red Deer Glen",
    landmarkStyle: "misty Highland glen and heather moor inspired scene",
    locationStyle: "Scottish Highlands inspired deer and mountain moor landscape",
    compositionSignature: "heather foreground, red deer stag midground, misty glen and mountains behind",
    background: "layered Highland mountains, low mist, moody gray sky, distant loch glimmer",
    midground: "red deer stag standing calmly in heather, natural scale, no aggressive rut fight",
    foreground: "purple heather, wet grass, stones, small stream",
    defaultWildlife: "Elk",
    wildlifeBehavior: "red deer stag with realistic antlers standing calmly in a Highland glen, natural posture and scale",
    bestSeason: "autumn rut season as peaceful non-fighting moment",
    bestLight: "soft misty sunrise light",
    cameraLook: "moody Highland wildlife photograph, restrained color, natural atmosphere",
    realismLocks: "accurate red deer anatomy, realistic mist, no castles, no roads",
    avoidTerms: "no people, no roads, no buildings, no fighting stags",
    caption: "Misty morning in red deer country.",
    hashtags: ["#Scotland", "#Highlands", "#RedDeer", "#Wildlife", "#Nature"],
    viralScore: 90,
  }),
  p({
    id: "australia-kangaroo-uluru-outback",
    collection: "World Scenic Wildlife",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Northern Territory, Australia",
    parkName: "Uluru-Kata Tjuta Region",
    title: "Australian Outback Kangaroo Sunset",
    landmarkStyle: "red desert and sandstone monolith region inspired scene",
    locationStyle: "Australian outback inspired red desert wildlife landscape",
    compositionSignature: "spinifex foreground, kangaroo midground, red sandstone monolith silhouette behind",
    background: "red sandstone monolith-like landform, wide desert sky, warm sunset clouds",
    midground: "kangaroo standing calmly in open desert plain, natural posture and scale",
    foreground: "spinifex grass, red sand, desert flowers, small stones",
    defaultWildlife: "Mule Deer",
    wildlifeBehavior: "red kangaroo standing calmly in outback desert, realistic tail balance, long hind legs and natural posture",
    bestSeason: "dry season golden hour",
    bestLight: "warm sunset glow across red sand",
    cameraLook: "outback travel wildlife photo, natural desert color, clean social composition",
    realismLocks: "accurate kangaroo anatomy, realistic red sand, no people, no roads",
    avoidTerms: "no tourists, no cars, no roads, no buildings",
    caption: "Outback quiet under a red desert sky.",
    hashtags: ["#Australia", "#Outback", "#Kangaroo", "#Wildlife", "#Nature"],
    viralScore: 89,
  }),
  p({
    id: "south-africa-penguins-boulders",
    collection: "World Scenic Wildlife",
    region: "USA / Canada",
    country: "USA / Canada",
    stateOrProvince: "Western Cape, South Africa",
    parkName: "Table Mountain National Park / Boulders Coast",
    title: "Cape Penguin Granite Coast",
    landmarkStyle: "granite boulder beach and Cape coast inspired scene",
    locationStyle: "South African Cape coast inspired penguin wildlife landscape",
    compositionSignature: "sand and boulders foreground, penguins midground, turquoise water and Cape sky behind",
    background: "clear coastal water, granite boulders, blue sky, distant Cape shoreline",
    midground: "African penguins standing calmly with natural spacing on sandy beach",
    foreground: "white sand, smooth granite stones, beach plants, small wave edge",
    defaultWildlife: "Great Blue Heron",
    wildlifeBehavior: "African penguins with black-and-white plumage standing calmly on beach, accurate flippers and posture",
    bestSeason: "clear summer or spring coastal light",
    bestLight: "soft morning beach light with clean water reflections",
    cameraLook: "bright coastal wildlife photo, crisp penguin detail, natural turquoise water",
    realismLocks: "accurate penguin anatomy, no crowds, realistic beach, no buildings",
    avoidTerms: "no people, no boardwalk, no signs, no city buildings",
    caption: "Wild little lives on the Cape coast.",
    hashtags: ["#SouthAfrica", "#Penguins", "#CapeTown", "#Wildlife", "#Nature"],
    viralScore: 88,
  }),
];

const EXISTING_WITH_COLLECTIONS: ExpandedScenicImagePreset[] = SCENIC_IMAGE_PRESETS.map((preset) => ({
  ...preset,
  collection: collectionForExistingPreset(preset),
}));

export const ALL_SCENIC_IMAGE_PRESETS: ExpandedScenicImagePreset[] = [
  ...EXISTING_WITH_COLLECTIONS,
  ...MORE_PRESETS,
];

export function getEnhancedScenicPresetById(id: string): ExpandedScenicImagePreset {
  return ALL_SCENIC_IMAGE_PRESETS.find((preset) => preset.id === id) ?? ALL_SCENIC_IMAGE_PRESETS[0];
}

export function getRandomEnhancedScenicPreset(options: {
  region?: ScenicImageRegion;
  collection?: ScenicCollection;
} = {}): ExpandedScenicImagePreset {
  const pool = ALL_SCENIC_IMAGE_PRESETS.filter((preset) => {
    if (options.region && preset.region !== options.region) return false;
    if (options.collection && preset.collection !== options.collection) return false;
    return true;
  });
  return pool[Math.floor(Math.random() * pool.length)] ?? ALL_SCENIC_IMAGE_PRESETS[0];
}

export function getEnhancedViralScenicPreset(collection?: ScenicCollection): {
  preset: ExpandedScenicImagePreset;
  mood: ScenicImageMood;
  aspectRatio: ScenicImageAspectRatio;
} {
  const pool = collection
    ? ALL_SCENIC_IMAGE_PRESETS.filter((preset) => preset.collection === collection)
    : ALL_SCENIC_IMAGE_PRESETS;
  const sorted = [...pool].sort((a, b) => b.viralScore - a.viralScore);
  const top = sorted.slice(0, 10);
  return {
    preset: top[Math.floor(Math.random() * top.length)] ?? ALL_SCENIC_IMAGE_PRESETS[0],
    mood: "Facebook Viral Nature Post",
    aspectRatio: Math.random() > 0.5 ? "9:16" : "4:5",
  };
}
